CREATE TABLE IF NOT EXISTS members(
  id UUID PRIMARY KEY,
  name VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS emails(
  id UUID PRIMARY KEY,
  member_id UUID NOT NULL REFERENCES members(id) ON UPDATE CASCADE ON DELETE CASCADE,
  email TEXT NOT NULL DEFAULT '' UNIQUE,
  activation BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL
);
